apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./dummy-test-repo/apps/production
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  prune: true
