name: Build Go binary (non-main)

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'bin/get-diffable'

jobs:
  build:
    name: Build
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Go build
        run: go build -ldflags="-w -s" -o bin/get-diffable .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated build of Go binary
