# Run locally: https://github.com/github/super-linter/blob/main/docs/run-linter-locally.md#run-the-container-locally
# docker pull github/super-linter:latest
# docker run --rm -e RUN_LOCAL=true -e USE_FIND_ALGORITHM=true -v $(pwd):/tmp/lint github/super-linter

name: GitHub Super-Linter

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
